## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('fncs-sample-simulator',
                                 ['fncs', 'applications'])
    obj.source = 'fncs-sample-simulator.cc'

