## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('master-example',
                                 ['dnp3', 'point-to-point', 'internet', 'applications'])
    obj.source = 'master.cc'
