# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
# Copyright (c) 2017-2019, Battelle Memorial Institute; Lawrence Livermore National Security, LLC; Alliance for Sustainable Energy, LLC.  See the top-level NOTICE for additional details. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

import os

from waflib import Options

def options(opt):
   opt.add_option('--with-zmq',
                   help=('Installation prefix for ZMQ'),
                   dest='with_zmq', default='/usr/local')
   opt.add_option('--with-helics',
                   help=('Path to HELICS for federated simulator integration'),
                   default='', dest='with_helics')

def configure(conf):
    if Options.options.with_zmq:
        if os.path.isdir(Options.options.with_zmq):
            conf.msg("Checking for libzmq.so location", ("%s (given)" % Options.options.with_zmq))
            conf.env['WITH_ZMQ'] = os.path.abspath(Options.options.with_zmq)

    if (not conf.env['WITH_ZMQ']):
        conf.env['MODULES_NOT_BUILT'].append('helics')
        return

    if Options.options.with_helics:
        if os.path.isdir(Options.options.with_helics):
            conf.msg("Checking for HELICS location", ("%s (given)" % Options.options.with_helics))
            conf.env['WITH_HELICS'] = os.path.abspath(Options.options.with_helics)
    # else:
        # bake.py uses ../../build, while ns-3-dev uses ../helics
    if not conf.env['WITH_HELICS']:
        conf.msg("Checking for HELICS location", False)
        conf.report_optional_feature("helics", "HELICS Integration", False,
                                     "HELICS not enabled (see option --with-helics)")
        # Add this module to the list of modules that won't be built
        # if they are enabled.
        conf.env['MODULES_NOT_BUILT'].append('helics')
        return

    zmq_test_code = '''
#include <zmq.h>
int main()
{
    void *context = zmq_ctx_new();
    (void) zmq_term(context);
    return 0;
}
'''

    helics_test_code = '''
int main()
{
    return 0;
}

'''

    conf.env.append_value('NS3_MODULE_PATH', os.path.abspath(os.path.join(conf.env['WITH_ZMQ'], 'build', 'default')))
    conf.env.append_value('NS3_MODULE_PATH', os.path.abspath(os.path.join(conf.env['WITH_ZMQ'], 'lib')))
    conf.env.append_value('NS3_MODULE_PATH', os.path.abspath(os.path.join(conf.env['WITH_ZMQ'], 'lib64')))
    conf.env['INCLUDES_ZMQ'] = [os.path.abspath(os.path.join(conf.env['WITH_ZMQ'], 'include'))]
    conf.env['LIBPATH_ZMQ'] = [
            os.path.abspath(os.path.join(conf.env['WITH_ZMQ'], 'build', 'default')),
            os.path.abspath(os.path.join(conf.env['WITH_ZMQ'], 'lib')),
            os.path.abspath(os.path.join(conf.env['WITH_ZMQ'], 'lib64'))
        ]
    conf.env['DEFINES_ZMQ'] = ['HAVE_ZMQ']
    conf.env['ZMQ'] = conf.check(fragment=zmq_test_code, lib='zmq', libpath=conf.env['LIBPATH_ZMQ'], use='ZMQ')
    conf.env.append_value('LIB_ZMQ', 'zmq')
    conf.report_optional_feature("zmq", "ZMQ Integration", conf.env['ZMQ'], "zmq library not found")


    conf.env.append_value('NS3_MODULE_PATH', os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'build', 'default')))
    conf.env.append_value('NS3_MODULE_PATH', os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib', 'helics')))
    conf.env.append_value('NS3_MODULE_PATH', os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib')))

    conf.env['INCLUDES_HELICS'] = [
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'include')),
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'include/helics'))
        ]
    conf.env['LIBPATH_HELICS'] = [
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'build', 'default')),
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib')),
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib', 'helics')),
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib64')),
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib64', 'helics'))
        ]
    conf.env['RPATH_HELICS'] = [
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib')),
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib', 'helics')),
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib64')),
            os.path.abspath(os.path.join(conf.env['WITH_HELICS'], 'lib64', 'helics'))
    ]

    conf.env['DEFINES_HELICS'] = ['NS3_HELICS']

    # Look for HELICS library
    # HELICS 2.3+: helics-shared, helics-sharedd
    # HELICS pre-2.3: helics-static, helics-staticd
    possible_helics_lib_names = ['helics-shared', 'helics-sharedd', 'helics-static', 'helics-staticd']
    for try_helics_lib in possible_helics_lib_names:
        retval = conf.check_nonfatal(fragment=helics_test_code, lib=try_helics_lib, libpath=conf.env['LIBPATH_HELICS'], use='HELICS')
        if retval:
            conf.env['HELICS'] = retval
            conf.env.append_value('LIB_HELICS', [try_helics_lib])
            break

    conf.env.append_value('INCLUDES', conf.env['INCLUDES_HELICS'])

    conf.report_optional_feature("helics", "HELICS Integration", conf.env['HELICS'], "HELICS library not found")

    if conf.env['HELICS']:
        conf.env['ENABLE_HELICS'] = True
    else:
        # Add this module to the list of modules that won't be built
        # if they are enabled.
        conf.env['MODULES_NOT_BUILT'].append('helics')

    # if HELICS is enabled, we must use c++14 instead of c++11
    if conf.env['HELICS']:
        for index,flag in enumerate(conf.env['CXXFLAGS']):
            if 'c++11' in flag:
                conf.env['CXXFLAGS'][index] = '-std=c++14'
                break
        print(conf.env['CXXFLAGS'])

def build(bld):
    if 'helics' in bld.env['MODULES_NOT_BUILT']:
        return

    module = bld.create_ns3_module('helics', ['core', 'internet', 'dnp3']) #Dnp3 needed by NATIG
    module.source = [
        'model/helics.cc',
        'model/helics-application.cc',
        #NATIG
        'model/dnp3-application-new.cc',
        ####
        'model/helics-filter-application.cc',
        'model/helics-static-sink-application.cc',
        'model/helics-static-source-application.cc',
        'model/helics-simulator-impl.cc',
        'model/helics-id-tag.cc',
        'helper/helics-helper.cc',
        #NATIG
        'helper/dnp3-application-helper-new.cc',
        ####
        ]
    module_test = bld.create_ns3_module_test_library('helics')
    module_test.source = [
        'test/helics-test-suite.cc',
        ]

    if bld.env['ENABLE_HELICS']:
        module.use.extend(['HELICS', 'ZMQ'])

    headers = bld(features='ns3header')
    headers.module = 'helics'
    headers.source = [
        'model/helics.h',
        'model/helics-application.h',
        #NATIG
        'model/dnp3-application-new.h',
        ####
        'model/helics-filter-application.h',
        'model/helics-static-sink-application.h',
        'model/helics-static-source-application.h',
        'model/helics-simulator-impl.h',
        'model/helics-id-tag.h',
        'helper/helics-helper.h',
        #NATIG
        'helper/dnp3-application-helper-new.h',
        ####
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

